name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"
          cache: "pip"
      - name: install dependencies
        shell: bash
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          python -m pip install wheel

          # for wxPython
          sudo apt install libnotify4

          # for numpy
          #sudo apt install gfortran libopenblas-dev liblapack-dev pkg-config

          python -m pip install pycairo
          python -m pip install PyGObject==3.50.0
          python -m pip install numpy

          python -m pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.2-cp311-cp311-linux_x86_64.whl

          python -m pip install -r requirements.txt
          # for networkx
          python -m pip install pandas
          python -m pip install pyarrow
      - name: Run Tests
        shell: bash
        run: |
          pytest
      - name: Type Check with Mypy
        shell: bash
        run: |
          python -m pip install mypy
          python -m mypy --output json | python .github/mypy-github-formatter
        continue-on-error: true
